=== cnshsliu/cflow/schemas/wft.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) by Altova 
	(XMLSpy) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:cf="http://lkh.com/cflow" targetNamespace="http://lkh.com/cflow">
	<xs:simpleType name="aclType">
		<xs:restriction base="xs:string">
			<xs:pattern value="private|group|public" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="actorType">
		<xs:restriction base="xs:string">
			<xs:pattern value="role|person|group|RefertoNode" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="message">
		<xs:simpleContent>
			<xs:extension base="xs:string" />
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="attachmentType">
		<xs:restriction base="xs:string">
			<xs:pattern value="text|url|int|float|netext" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="mailto">
		<xs:attribute name="type" type="cf:actorType" use="required" />
		<xs:attribute name="whom" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="smsto">
		<xs:attribute name="type" type="cf:actorType" use="required" />
		<xs:attribute name="whom" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="taskto">
		<xs:sequence>
			<xs:element name="exceptme" type="cf:exceptme"
				maxOccurs="unbounded" minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="cf:actorType" use="required">
			<xs:annotation>
				<xs:documentation>
					role or person are two possilbe tyes for workflow
					template. For a process, type must be "person"
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="whom" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Role name or user id depends on the type of taskto
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="status" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					在进程中记录该用户的工作完成情况。在模板中不起作用；
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>

	</xs:complexType>
	<xs:complexType name="attachment">
		<xs:attribute name="type" type="cf:attachmentType"
			use="required" />
		<xs:attribute name="label" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					The promot for input
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="optional"
			default="">
			<xs:annotation>
				<xs:documentation>
					For template, value is normally not specified. for
					process, value should be input by user.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="attname" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					name of the attribute, should be a valid
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="usrid" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="sendmail">
		<xs:sequence>
			<xs:element name="mailto" type="cf:mailto" />
			<xs:element name="message" type="cf:message" />
		</xs:sequence>
		<xs:attribute name="subject" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="sendsms">
		<xs:sequence>
			<xs:element name="smsto" type="cf:smsto" />
			<xs:element name="message" type="cf:message" />
		</xs:sequence>
		<xs:attribute name="subject" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="role">
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>the name of a role</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Normally, the participant of a role is specified
					while process run. Workflow designer could assign value to a
					particular role as well.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="robotActions">
		<xs:choice>
			<xs:element name="sendmail" type="cf:sendmail" />
			<xs:element name="sendsms" type="cf:sendsms" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="nextType">
		<xs:attribute name="option" type="xs:string" default="DEFAULT">
			<xs:annotation>
				<xs:documentation>If options present for more than one next element,
					user must choice among these options, the route will depend on
					user's choice.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="targetID" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>id of the next node pointed to.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="node">
		<xs:annotation>
			<xs:documentation>a node of workflow</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="taskto" type="cf:taskto" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="preactions" type="cf:robotActions"
				minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Actions to be taken automaticlaly before any
						other acitons could occurs.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="sendmail" type="cf:sendmail"
				minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Send out an email
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="sendsms" type="cf:sendsms"
				minOccurs="0">
				<xs:annotation>
					<xs:documentation>Send out an SMS</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="attachment" type="cf:attachment"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="script" minOccurs="0">
				<xs:complexType mixed="false">
					<xs:simpleContent>
						<xs:extension base="xs:string" />
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="next" type="cf:nextType"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Occurance of next is 0 means that the node's
						next node is "end".
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="postactions" type="cf:robotActions"
				minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Actions to be taken automatically before this
						task could complete.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="mpcdc" maxOccurs="1" minOccurs="0"
				type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Multiple Person Completion Decision Code
					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element name="oec" maxOccurs="1" minOccurs="0"
				type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Option Evaluation Code
					</xs:documentation>
				</xs:annotation>

			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="cf:nodeType" use="optional"
			default="task">
			<xs:annotation>
				<xs:documentation>
					Whether this node is an automatic node which will be
					executed automatically.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="id" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="title" type="xs:string" />
		<xs:attribute name="customizer" type="xs:string"></xs:attribute>
		<xs:attribute name="x" type="xs:int" />
		<xs:attribute name="y" type="xs:int" />
		<xs:attribute name="subWftUID" type="xs:string" />
		<xs:attribute name="subWftWG" type="xs:string" />
		<xs:attribute name="yy" type="xs:integer" />
		<xs:attribute name="mm" type="xs:integer" />
		<xs:attribute name="dd" type="xs:integer" />
		<xs:attribute name="hh" type="xs:integer" />
		<xs:attribute name="mi" type="xs:integer" />
		<xs:attribute name="timeingType" type="xs:string" />
		<xs:attribute name="mpsm" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					Multiple Person Sync Mode
				</xs:documentation>
			</xs:annotation>

		</xs:attribute>
		<xs:attribute name="acquirable" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="acqThreshold" type="xs:int" default="1"></xs:attribute>
		<xs:attribute name="allowRoleChange" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="roleToChange" type="xs:string"
			default="all">
		</xs:attribute>
		<xs:attribute name="allowDelegate" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="allowAdhoc" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="allowBack" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="repeatthresholdtype" type="xs:string"></xs:attribute>
		<xs:attribute name="repeatthreshold" type="xs:string"></xs:attribute>
		<xs:attribute name="repeatcron" type="xs:string"></xs:attribute>
		<xs:attribute name="form" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:element name="workflow">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="role" type="cf:role" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="node" type="cf:node" minOccurs="0"
					maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="owner" type="xs:string" use="required" />
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="origin" type="xs:string"></xs:attribute>
			<xs:attribute name="memo" type="xs:string" use="optional" />
			<xs:attribute name="customizer" type="xs:string"></xs:attribute>
			<xs:attribute name="pbo" type="xs:string"></xs:attribute>
			<xs:attribute name="acl" type="cf:aclType" use="required" />
			<xs:attribute name="lastModified" type="xs:dateTime"
				use="required" />
			<xs:attribute name="created" type="xs:dateTime"
				use="required" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="processStatusType">
		<xs:restriction base="xs:string">
			<xs:pattern value="running|suspended|finished|canceled" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="nodeType">
		<xs:restriction base="xs:string">
			<xs:pattern value="task|notify|sub|timer|and|or|round|script|start|end|ground" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="workStatusType">
		<xs:restriction base="xs:string">
			<xs:pattern value="running|suspended|finished|ignored" />
		</xs:restriction>
	</xs:simpleType>
	<!--Process definition start here -->
	<xs:complexType name="work">
		<xs:sequence>
			<xs:element name="taskto" type="cf:taskto"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Person to whom this task will be delivered.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="attachment" type="cf:attachment"
				minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						An attachment is an information need to be input
						by "taskto"
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="options" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="option" type="xs:string"
							maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="isMultipleSelection"
						type="xs:boolean" default="false" />
				</xs:complexType>
			</xs:element>
			<xs:element name="mpcdc" maxOccurs="1" minOccurs="0"
				type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Multiple Person Completion Decision Code
					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element name="oec" maxOccurs="1" minOccurs="0"
				type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Option Evaluation Code
					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element name="log" type="cf:log" maxOccurs="unbounded"
				minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="sessid" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					session id a UID string
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="roundid" type="xs:string"></xs:attribute>
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="title" type="xs:string" />
		<xs:attribute name="customizer" type="xs:string"></xs:attribute>
		<xs:attribute name="type" type="xs:string" />
		<xs:attribute name="nodeid" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					id of corresponding workflow node.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="createdAt" type="xs:dateTime">
			<xs:annotation>
				<xs:documentation>
					Time when this work was yarked
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="completedAt" type="xs:dateTime">
			<xs:annotation>
				<xs:documentation>
					Time when this work was completed
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="completedBy" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					Who commit this work
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="status" type="cf:workStatusType"
			default="running" />
		<xs:attribute name="decision" type="xs:string"
			default="DEFAULT">
			<xs:annotation>
				<xs:documentation>
					The option user selected
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="mpsm" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					Multiple Person Sync Mode
				</xs:documentation>
			</xs:annotation>

		</xs:attribute>
		<xs:attribute name="sysmsg" type="xs:string">
			<xs:annotation>
				<xs:documentation>System Message</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="acquirable" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="acqThreshold" type="xs:int" default="1"></xs:attribute>
		<xs:attribute name="allowDelegate" type="xs:boolean"
			default="true">
		</xs:attribute>
		<xs:attribute name="allowAdhoc" type="xs:boolean"
			default="true">
		</xs:attribute>
		<xs:attribute name="repeatthresholdtype" type="xs:string"></xs:attribute>
		<xs:attribute name="repeatthreshold" type="xs:string"></xs:attribute>
		<xs:attribute name="repeatcron" type="xs:string"></xs:attribute>
		<xs:attribute name="form" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ProcessT">
		<xs:annotation>
			<xs:documentation>用于记录</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="role" type="cf:role" minOccurs="0"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Role pair (name and value) for a template,
						normally the value does not present but workflow
						designer can set value for a role whenever
						needed. For a process, the value should present.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="work" type="cf:work"
				maxOccurs="unbounded" />
			<xs:element name="team" type="cf:teamType" maxOccurs="1"
				minOccurs="1">
			</xs:element>
			<xs:element name="attachment" type="cf:attachment"
				maxOccurs="unbounded" minOccurs="0">
				<xs:annotation>
					<xs:documentation>用于记录流程级参数</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string">
			<xs:annotation>
				<xs:documentation>id of the process</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="roundid" type="xs:string"></xs:attribute>
		<xs:attribute name="startby" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					userid who has started this process
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="startat" type="xs:dateTime">
			<xs:annotation>
				<xs:documentation>
					When this process was started
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="endat" type="xs:dateTime">
			<xs:annotation>
				<xs:documentation>
					When this process finished
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="status" type="cf:processStatusType">
			<xs:annotation>
				<xs:documentation>
					The status of the process
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="wftid" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					id of the corresponding workflow template
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="origin" type="xs:string"></xs:attribute>
		<xs:attribute name="wftname" type="xs:string" />
		<xs:attribute name="customizer" type="xs:string"></xs:attribute>
		<xs:attribute name="teamid" type="xs:string" />
		<xs:attribute name="pbo" type="xs:string"></xs:attribute>
		<xs:attribute name="lastError" type="xs:string"></xs:attribute>
		<xs:attribute name="parentProcessId" type="xs:string" />
		<xs:attribute name="parentProcessNodeId" type="xs:string" />
		<xs:attribute name="parentProcessSessId" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:element name="process" type="cf:ProcessT">
		<xs:annotation>
			<xs:documentation>Process is instantiated from a workflow template
			</xs:documentation>
		</xs:annotation>
	</xs:element>
	<!--Process definition end here -->

	<xs:complexType name="log">
		<xs:sequence>
			<xs:element name="attachment" type="cf:attachment" maxOccurs="unbounded" minOccurs="0"></xs:element>
		</xs:sequence>
		<xs:attribute name="usrid" type="xs:string"></xs:attribute>
		<xs:attribute name="timestamp" type="xs:dateTime"></xs:attribute>
		<xs:attribute name="option" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:simpleType name="mpsmType">
		<xs:restriction base="xs:string"></xs:restriction>
	</xs:simpleType>


	<xs:complexType name="exceptme">
		<xs:attribute name="nodeid" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="delegate">
		<xs:attribute name="fromuid" type="xs:string"></xs:attribute>
		<xs:attribute name="touid" type="xs:string"></xs:attribute>
		<xs:attribute name="delegateat" type="xs:dateTime"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="teamType">
		<xs:sequence>
			<xs:element name="role" type="cf:role" maxOccurs="unbounded" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== cnshsliu/cflow/data/vault/U3306-612C43C4-FCC4-4463-BC60-78B940DF5709.xml
<?xml version="1.0" encoding="UTF-8"?>
<cf:workflow xsi:schemaLocation="http://lkh.com/cflow ../schemas/wft.xsd" name="差旅申请" owner="U3306" acl="private" lastModified="2010-12-22T22:54:05" created="2010-12-22T22:54:05" xmlns:cf="http://lkh.com/cflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <node id="19BD4CFD-B577-A0CD-DFB0-78B940D53AF0" type="start" title="Start" name="Start" x="27" y="204">
    <next targetID="02C971E6-BB69-8320-295F-78BA548A900F"/>
  </node>
  <node id="9439CAF5-6FDD-A248-C9C2-78B940D518C5" type="end" title="End" name="End" x="652" y="340">
    <next targetID="9439CAF5-6FDD-A248-C9C2-78B940D518C5"/>
  </node>
  <node id="02C971E6-BB69-8320-295F-78BA548A900F" type="task" title="Task" name="出差申请" x="119" y="206" acquirable="false" acqThreshold="0" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="null" mpsm="null">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <attachment type="text" label="出差理由" attname="出差理由" value=""/>
    <next option="2.提交审批" targetID="5E926926-D6C8-76BC-F281-78BCD2A53A86"/>
    <next option="1.暂存" targetID="49B64D32-7695-AD57-6325-7FDD346238CC"/>
    <next option="3.放弃(d)" targetID="C1218C63-C17F-DB82-8D39-7FDD312D7AED"/>
  </node>
  <node id="5E926926-D6C8-76BC-F281-78BCD2A53A86" type="task" title="是否允许出差" name="是否允许出差" x="195" y="207" acquirable="false" acqThreshold="0" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="null" mpsm="null">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next option="不允许" targetID="4492E67E-C721-9E1B-58DC-78C79DE02E1D"/>
    <next option="允许" targetID="409309E9-9A7D-A5C8-1FFD-78C0217D6907"/>
  </node>
  <node id="409309E9-9A7D-A5C8-1FFD-78C0217D6907" type="task" title="预定产品操作说明" name="预定产品" x="206" y="122" acquirable="false" acqThreshold="0" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="null" mpsm="null">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next targetID="7BDEDE14-F0AA-2EC0-CA76-78C093A3467E"/>
  </node>
  <node id="7BDEDE14-F0AA-2EC0-CA76-78C093A3467E" type="task" title="请确定预定产品是否完备的说明" name="请确定预定产品是否完备" x="271" y="121" acquirable="false" acqThreshold="0" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="null" mpsm="null">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <attachment type="text" label="留言" attname="留言" value=""/>
    <next option="完备" targetID="C2682227-DA3E-AA76-AC82-78C18B388CC8"/>
    <next option="不完备" targetID="C89EC96D-E0DC-056F-6ABD-78C3F50FFDE3"/>
  </node>
  <node id="C2682227-DA3E-AA76-AC82-78C18B388CC8" type="task" title="出差完成后，请点“完成”按钮" name="出差中" x="505" y="121" acquirable="false" acqThreshold="0" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="null" mpsm="null">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <attachment type="text" label="差旅留言" attname="差旅留言" value=""/>
    <next option="本次出差已结束" targetID="814C0C19-2718-CF20-F0AF-78C2ACE4E788"/>
    <next option="本次出差未结束" targetID="5448B9EE-BA0B-E540-33BB-78C62C7AF46F"/>
    <next option="本次出差需要加订差旅" targetID="C89EC96D-E0DC-056F-6ABD-78C3F50FFDE3"/>
  </node>
  <node id="814C0C19-2718-CF20-F0AF-78C2ACE4E788" type="task" title="额外费用填写说明" name="出差结束，请填写额外费用" x="607" y="36" acquirable="false" acqThreshold="0" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="null" mpsm="null">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next targetID="4492E67E-C721-9E1B-58DC-78C79DE02E1D"/>
  </node>
  <node id="C89EC96D-E0DC-056F-6ABD-78C3F50FFDE3" type="or" title="OR" name="OR" x="232" y="16">
    <next targetID="409309E9-9A7D-A5C8-1FFD-78C0217D6907"/>
  </node>
  <node id="5448B9EE-BA0B-E540-33BB-78C62C7AF46F" type="or" title="OR" name="OR" x="481" y="34">
    <next targetID="6FC9F98A-B4A3-2E1C-B42D-78C666231DF7"/>
  </node>
  <node id="6FC9F98A-B4A3-2E1C-B42D-78C666231DF7" type="or" title="OR" name="OR" x="532" y="25">
    <next targetID="C2682227-DA3E-AA76-AC82-78C18B388CC8"/>
  </node>
  <node id="4492E67E-C721-9E1B-58DC-78C79DE02E1D" type="or" title="OR" name="OR" x="655" y="211">
    <next targetID="9439CAF5-6FDD-A248-C9C2-78B940D518C5"/>
  </node>
  <node id="C1218C63-C17F-DB82-8D39-7FDD312D7AED" type="or" title="OR" name="OR" x="269" y="338">
    <next targetID="9439CAF5-6FDD-A248-C9C2-78B940D518C5"/>
  </node>
  <node id="49B64D32-7695-AD57-6325-7FDD346238CC" type="or" title="OR" name="OR" x="151" y="50">
    <next targetID="B85C293F-509A-7DD5-0720-7FDD36BBD063"/>
  </node>
  <node id="B85C293F-509A-7DD5-0720-7FDD36BBD063" type="or" title="OR" name="OR" x="37" y="86">
    <next targetID="02C971E6-BB69-8320-295F-78BA548A900F"/>
  </node>
</cf:workflow>

=== cnshsliu/cflow/data/vault/U3306-CDEA6829-D15B-B531-9D33-96622EFC978C.xml
<?xml version="1.0" encoding="UTF-8"?>
<cf:workflow xsi:schemaLocation="http://lkh.com/cflow ../schemas/wft.xsd" name="callURLTest" owner="U3306" acl="private" lastModified="2010-11-29T16:03:52" created="2010-11-29T16:03:52" xmlns:cf="http://lkh.com/cflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <node id="5CC4CFA1-6533-45D5-94AD-59F4A2A296DC" type="start" title="Start" name="Start" x="26" y="92">
    <next targetID="F3518383-8E11-E6D2-A536-59F4CA5D114B"/>
  </node>
  <node id="022434F3-87E5-21E2-4105-59F4A2A9FD68" type="end" title="End" name="End" x="120" y="369">
    <next targetID="022434F3-87E5-21E2-4105-59F4A2A9FD68"/>
  </node>
  <node id="F3518383-8E11-E6D2-A536-59F4CA5D114B" type="task" title="请输入请假天数和请假原因" name="请假申请" x="116" y="109" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" mpsm="1">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <attachment type="int" label="请假天数" attname="days" value=""/>
    <attachment type="text" label="请假原因" attname="reason" value=""/>
    <next option="Continue" targetID="27F2E181-3305-3955-F5F2-96446276DC7E"/>
    <next option="Cancel" targetID="022434F3-87E5-21E2-4105-59F4A2A9FD68"/>
  </node>
  <node id="7CE979C9-5530-79C0-768F-59F637566ECF" type="task" title="恭喜，你的请假申请已通过批准" name="请假已通过" x="261" y="116" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" mpsm="1">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next targetID="A32757D6-75B9-88BB-F75D-968ECD9BA5E5"/>
  </node>
  <node id="348CAF86-53E0-A373-6F51-59F657CCCF0E" type="task" title="你的请假申请被拒绝&#xD;" name="请假申请被拒" x="396" y="45" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" mpsm="1">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next targetID="A32757D6-75B9-88BB-F75D-968ECD9BA5E5"/>
  </node>
  <node id="27F2E181-3305-3955-F5F2-96446276DC7E" type="script" title="Script" name="Script" x="212" y="40">
    <script>URL:http://localhost:8080/HR/LeaveDecision</script>
    <next option="long" targetID="348CAF86-53E0-A373-6F51-59F657CCCF0E"/>
    <next option="short" targetID="7CE979C9-5530-79C0-768F-59F637566ECF"/>
    <next targetID="A32757D6-75B9-88BB-F75D-968ECD9BA5E5"/>
  </node>
  <node id="A32757D6-75B9-88BB-F75D-968ECD9BA5E5" type="or" title="OR" name="OR" x="431" y="155">
    <next targetID="F3518383-8E11-E6D2-A536-59F4CA5D114B"/>
  </node>
</cf:workflow>

=== cnshsliu/cflow/data/istwft/tester1/fb47ff33087543a4ad6c081b5cb98b48.xml
<?xml version="1.0" encoding="UTF-8"?><cf:workflow xsi:schemaLocation="http://lkh.com/cflow ../schemas/wft.xsd" name="tobedelete" owner="LKH" acl="private" lastModified="2011-03-19T04:18:58" created="2011-03-19T04:18:58" xmlns:cf="http://lkh.com/cflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><node id="id_start" type="start" title="Start" name="Start" x="27" y="213">
 <next targetID="id_1"/></node><node id="id_end" type="end" title="End" name="End" x="738" y="213">
 <next targetID="id_end"/></node><node id="id_1" type="task" title="mpsm_2" name="Task" x="356" y="203" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="" mpsm="3">
 <taskto type="role" whom="Approver"/>
 <mpcdc>if(finished>=2) return "true"; else return "false";</mpcdc>
 <oec>if(finished>=2) return "4"; else return "DEFAULT";</oec>
 <next option="4" targetID="id_4"/>
 <next option="DEFAULT" targetID="id_end"/>
 </node><node id="id_4" type="task" title="totalequalsto4" name="Task" x="356" y="203" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="" mpsm="1">
 <taskto type="role" whom="starter"/>
 <mpcdc/>
 <oec/>
 <next targetID="id_end"/>
  </node></cf:workflow>
