=== cnshsliu/cflow/schemas/wft.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) by Altova 
	(XMLSpy) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:cf="http://lkh.com/cflow" targetNamespace="http://lkh.com/cflow">
	<xs:simpleType name="aclType">
		<xs:restriction base="xs:string">
			<xs:pattern value="private|group|public" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="actorType">
		<xs:restriction base="xs:string">
			<xs:pattern value="role|person|group|RefertoNode" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="message">
		<xs:simpleContent>
			<xs:extension base="xs:string" />
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="attachmentType">
		<xs:restriction base="xs:string">
			<xs:pattern value="text|url|int|float|netext" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="mailto">
		<xs:attribute name="type" type="cf:actorType" use="required" />
		<xs:attribute name="whom" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="smsto">
		<xs:attribute name="type" type="cf:actorType" use="required" />
		<xs:attribute name="whom" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="taskto">
		<xs:sequence>
			<xs:element name="exceptme" type="cf:exceptme"
				maxOccurs="unbounded" minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="cf:actorType" use="required">
			<xs:annotation>
				<xs:documentation>
					role or person are two possilbe tyes for workflow
					template. For a process, type must be "person"
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="whom" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Role name or user id depends on the type of taskto
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="status" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					在进程中记录该用户的工作完成情况。在模板中不起作用；
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>

	</xs:complexType>
	<xs:complexType name="attachment">
		<xs:attribute name="type" type="cf:attachmentType"
			use="required" />
		<xs:attribute name="label" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					The promot for input
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="optional"
			default="">
			<xs:annotation>
				<xs:documentation>
					For template, value is normally not specified. for
					process, value should be input by user.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="attname" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					name of the attribute, should be a valid
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="usrid" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="sendmail">
		<xs:sequence>
			<xs:element name="mailto" type="cf:mailto" />
			<xs:element name="message" type="cf:message" />
		</xs:sequence>
		<xs:attribute name="subject" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="sendsms">
		<xs:sequence>
			<xs:element name="smsto" type="cf:smsto" />
			<xs:element name="message" type="cf:message" />
		</xs:sequence>
		<xs:attribute name="subject" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="role">
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>the name of a role</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Normally, the participant of a role is specified
					while process run. Workflow designer could assign value to a
					particular role as well.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="robotActions">
		<xs:choice>
			<xs:element name="sendmail" type="cf:sendmail" />
			<xs:element name="sendsms" type="cf:sendsms" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="nextType">
		<xs:attribute name="option" type="xs:string" default="DEFAULT">
			<xs:annotation>
				<xs:documentation>If options present for more than one next element,
					user must choice among these options, the route will depend on
					user's choice.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="targetID" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>id of the next node pointed to.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="node">
		<xs:annotation>
			<xs:documentation>a node of workflow</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="taskto" type="cf:taskto" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="preactions" type="cf:robotActions"
				minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Actions to be taken automaticlaly before any
						other acitons could occurs.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="sendmail" type="cf:sendmail"
				minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Send out an email
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="sendsms" type="cf:sendsms"
				minOccurs="0">
				<xs:annotation>
					<xs:documentation>Send out an SMS</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="attachment" type="cf:attachment"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="script" minOccurs="0">
				<xs:complexType mixed="false">
					<xs:simpleContent>
						<xs:extension base="xs:string" />
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="next" type="cf:nextType"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Occurance of next is 0 means that the node's
						next node is "end".
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="postactions" type="cf:robotActions"
				minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Actions to be taken automatically before this
						task could complete.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="mpcdc" maxOccurs="1" minOccurs="0"
				type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Multiple Person Completion Decision Code
					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element name="oec" maxOccurs="1" minOccurs="0"
				type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Option Evaluation Code
					</xs:documentation>
				</xs:annotation>

			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="cf:nodeType" use="optional"
			default="task">
			<xs:annotation>
				<xs:documentation>
					Whether this node is an automatic node which will be
					executed automatically.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="id" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="title" type="xs:string" />
		<xs:attribute name="customizer" type="xs:string"></xs:attribute>
		<xs:attribute name="x" type="xs:int" />
		<xs:attribute name="y" type="xs:int" />
		<xs:attribute name="subWftUID" type="xs:string" />
		<xs:attribute name="subWftWG" type="xs:string" />
		<xs:attribute name="yy" type="xs:integer" />
		<xs:attribute name="mm" type="xs:integer" />
		<xs:attribute name="dd" type="xs:integer" />
		<xs:attribute name="hh" type="xs:integer" />
		<xs:attribute name="mi" type="xs:integer" />
		<xs:attribute name="timeingType" type="xs:string" />
		<xs:attribute name="mpsm" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					Multiple Person Sync Mode
				</xs:documentation>
			</xs:annotation>

		</xs:attribute>
		<xs:attribute name="acquirable" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="acqThreshold" type="xs:int" default="1"></xs:attribute>
		<xs:attribute name="allowRoleChange" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="roleToChange" type="xs:string"
			default="all">
		</xs:attribute>
		<xs:attribute name="allowDelegate" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="allowAdhoc" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="allowBack" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="repeatthresholdtype" type="xs:string"></xs:attribute>
		<xs:attribute name="repeatthreshold" type="xs:string"></xs:attribute>
		<xs:attribute name="repeatcron" type="xs:string"></xs:attribute>
		<xs:attribute name="form" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:element name="workflow">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="role" type="cf:role" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="node" type="cf:node" minOccurs="0"
					maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="owner" type="xs:string" use="required" />
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="origin" type="xs:string"></xs:attribute>
			<xs:attribute name="memo" type="xs:string" use="optional" />
			<xs:attribute name="customizer" type="xs:string"></xs:attribute>
			<xs:attribute name="pbo" type="xs:string"></xs:attribute>
			<xs:attribute name="acl" type="cf:aclType" use="required" />
			<xs:attribute name="lastModified" type="xs:dateTime"
				use="required" />
			<xs:attribute name="created" type="xs:dateTime"
				use="required" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="processStatusType">
		<xs:restriction base="xs:string">
			<xs:pattern value="running|suspended|finished|canceled" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="nodeType">
		<xs:restriction base="xs:string">
			<xs:pattern value="task|notify|sub|timer|and|or|round|script|start|end|ground" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="workStatusType">
		<xs:restriction base="xs:string">
			<xs:pattern value="running|suspended|finished|ignored" />
		</xs:restriction>
	</xs:simpleType>
	<!--Process definition start here -->
	<xs:complexType name="work">
		<xs:sequence>
			<xs:element name="taskto" type="cf:taskto"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Person to whom this task will be delivered.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="attachment" type="cf:attachment"
				minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						An attachment is an information need to be input
						by "taskto"
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="options" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="option" type="xs:string"
							maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="isMultipleSelection"
						type="xs:boolean" default="false" />
				</xs:complexType>
			</xs:element>
			<xs:element name="mpcdc" maxOccurs="1" minOccurs="0"
				type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Multiple Person Completion Decision Code
					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element name="oec" maxOccurs="1" minOccurs="0"
				type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Option Evaluation Code
					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element name="log" type="cf:log" maxOccurs="unbounded"
				minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="sessid" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					session id a UID string
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="roundid" type="xs:string"></xs:attribute>
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="title" type="xs:string" />
		<xs:attribute name="customizer" type="xs:string"></xs:attribute>
		<xs:attribute name="type" type="xs:string" />
		<xs:attribute name="nodeid" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					id of corresponding workflow node.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="createdAt" type="xs:dateTime">
			<xs:annotation>
				<xs:documentation>
					Time when this work was yarked
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="completedAt" type="xs:dateTime">
			<xs:annotation>
				<xs:documentation>
					Time when this work was completed
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="completedBy" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					Who commit this work
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="status" type="cf:workStatusType"
			default="running" />
		<xs:attribute name="decision" type="xs:string"
			default="DEFAULT">
			<xs:annotation>
				<xs:documentation>
					The option user selected
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="mpsm" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					Multiple Person Sync Mode
				</xs:documentation>
			</xs:annotation>

		</xs:attribute>
		<xs:attribute name="sysmsg" type="xs:string">
			<xs:annotation>
				<xs:documentation>System Message</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="acquirable" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="acqThreshold" type="xs:int" default="1"></xs:attribute>
		<xs:attribute name="allowDelegate" type="xs:boolean"
			default="true">
		</xs:attribute>
		<xs:attribute name="allowAdhoc" type="xs:boolean"
			default="true">
		</xs:attribute>
		<xs:attribute name="repeatthresholdtype" type="xs:string"></xs:attribute>
		<xs:attribute name="repeatthreshold" type="xs:string"></xs:attribute>
		<xs:attribute name="repeatcron" type="xs:string"></xs:attribute>
		<xs:attribute name="form" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ProcessT">
		<xs:annotation>
			<xs:documentation>用于记录</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="role" type="cf:role" minOccurs="0"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Role pair (name and value) for a template,
						normally the value does not present but workflow
						designer can set value for a role whenever
						needed. For a process, the value should present.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="work" type="cf:work"
				maxOccurs="unbounded" />
			<xs:element name="team" type="cf:teamType" maxOccurs="1"
				minOccurs="1">
			</xs:element>
			<xs:element name="attachment" type="cf:attachment"
				maxOccurs="unbounded" minOccurs="0">
				<xs:annotation>
					<xs:documentation>用于记录流程级参数</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string">
			<xs:annotation>
				<xs:documentation>id of the process</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="roundid" type="xs:string"></xs:attribute>
		<xs:attribute name="startby" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					userid who has started this process
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="startat" type="xs:dateTime">
			<xs:annotation>
				<xs:documentation>
					When this process was started
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="endat" type="xs:dateTime">
			<xs:annotation>
				<xs:documentation>
					When this process finished
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="status" type="cf:processStatusType">
			<xs:annotation>
				<xs:documentation>
					The status of the process
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="wftid" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					id of the corresponding workflow template
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="origin" type="xs:string"></xs:attribute>
		<xs:attribute name="wftname" type="xs:string" />
		<xs:attribute name="customizer" type="xs:string"></xs:attribute>
		<xs:attribute name="teamid" type="xs:string" />
		<xs:attribute name="pbo" type="xs:string"></xs:attribute>
		<xs:attribute name="lastError" type="xs:string"></xs:attribute>
		<xs:attribute name="parentProcessId" type="xs:string" />
		<xs:attribute name="parentProcessNodeId" type="xs:string" />
		<xs:attribute name="parentProcessSessId" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:element name="process" type="cf:ProcessT">
		<xs:annotation>
			<xs:documentation>Process is instantiated from a workflow template
			</xs:documentation>
		</xs:annotation>
	</xs:element>
	<!--Process definition end here -->

	<xs:complexType name="log">
		<xs:sequence>
			<xs:element name="attachment" type="cf:attachment" maxOccurs="unbounded" minOccurs="0"></xs:element>
		</xs:sequence>
		<xs:attribute name="usrid" type="xs:string"></xs:attribute>
		<xs:attribute name="timestamp" type="xs:dateTime"></xs:attribute>
		<xs:attribute name="option" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:simpleType name="mpsmType">
		<xs:restriction base="xs:string"></xs:restriction>
	</xs:simpleType>


	<xs:complexType name="exceptme">
		<xs:attribute name="nodeid" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="delegate">
		<xs:attribute name="fromuid" type="xs:string"></xs:attribute>
		<xs:attribute name="touid" type="xs:string"></xs:attribute>
		<xs:attribute name="delegateat" type="xs:dateTime"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="teamType">
		<xs:sequence>
			<xs:element name="role" type="cf:role" maxOccurs="unbounded" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== cnshsliu/cflow/data/model/Demo_RoleReference_en_US.xml
<?xml version="1.0" encoding="UTF-8"?><cf:workflow xsi:schemaLocation="http://lkh.com/cflow ../schemas/wft.xsd" name="Demo_RoleReference" memo="Demonstrate how to determine a task's undertaker with reference. The task of 'Check' will be done by Reviewer, but this task will not be dispatched to poeple who also take the role as Reviewer and did the fist task, say 'Review'; The task of 'Result' will be dispatched to who did the 'Review' task by role referencing machanism. " owner="tester1" acl="private" lastModified="2012-11-10T23:24:00" created="2012-11-10T23:24:00" xmlns:cf="http://lkh.com/cflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <role name="Reviwer"/>
  <role name="Reviewer"/>
  <node id="C18F90B7-8FA9-AD83-C0D8-EAD6804B3F48" type="start" title="Start" name="Start" x="28" y="228">
    <next targetID="BBD4A418-66CE-E2CA-0E37-EAD7FA87E900"/>
  </node>
  <node id="8EADD8E5-2A9F-8801-641B-EAD6804FEA64" type="end" title="End" name="End" x="433" y="223">
    <next targetID="8EADD8E5-2A9F-8801-641B-EAD6804FEA64"/>
  </node>
  <node id="BBD4A418-66CE-E2CA-0E37-EAD7FA87E900" type="task" title="Please reveiw the doc[br]This demo template show role referece and mutual exclusion. [br]To try it, you must start this workflow with a team contains a role of &quot;Reviewer&quot; which maps to at least two different people.  The first two tasks should be done by Reviewer, but the people who did the first one will not see the second task in his/her worklist, and the third task will be delivered to people who did the first task." name="Review" x="104" y="225" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="" mpsm="1">
    <taskto type="role" whom="Reviwer"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <attachment type="text" label="Reviewer_Comment" attname="reviewer_comment" value="Please input your comment"/>
    <next targetID="579A2CF4-ECB2-A8AB-84D1-EAD8625C11DD"/>
  </node>
  <node id="579A2CF4-ECB2-A8AB-84D1-EAD8625C11DD" type="task" title="Please chek the review" name="Check" x="190" y="225" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="" mpsm="1">
    <taskto type="role" whom="Reviewer">
      <exceptme nodeid="BBD4A418-66CE-E2CA-0E37-EAD7FA87E900"/>
    </taskto>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <attachment type="text" label="Checker Comment" attname="checker_comment" value=""/>
    <next targetID="AA8CC982-16D2-FD39-A448-EAE52A49CD1B"/>
  </node>
  <node id="AA8CC982-16D2-FD39-A448-EAE52A49CD1B" type="task" title="Task" name="Result" x="312" y="222" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="" mpsm="1">
    <taskto type="RefertoNode" whom="BBD4A418-66CE-E2CA-0E37-EAD7FA87E900"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next targetID="8EADD8E5-2A9F-8801-641B-EAD6804FEA64"/>
  </node>
</cf:workflow>

=== cnshsliu/cflow/data/istwft/peixin.baipx/2c3d60d46de143928eb07b7bd04d503d.xml
<cf:workflow xsi:schemaLocation="http://lkh.com/cflow ../schemas/wft.xsd" name="Leave Application" owner="aliyun" acl="private" lastModified="2012-11-30T07:21:44" created="2012-11-30T07:21:44" xmlns:cf="http://lkh.com/cflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <role name="Approver"/>
  <node id="5CC4CFA1-6533-45D5-94AD-59F4A2A296DC" type="start" title="Start" name="Start" x="26" y="92">
    <next targetID="F3518383-8E11-E6D2-A536-59F4CA5D114B" joints=""/>
  </node>
  <node id="022434F3-87E5-21E2-4105-59F4A2A9FD68" type="end" title="End" name="End" x="750" y="231">
    <next targetID="022434F3-87E5-21E2-4105-59F4A2A9FD68"/>
  </node>
  <node id="F3518383-8E11-E6D2-A536-59F4CA5D114B" type="task" title="Please input leave days and reason." name="Leave Application" x="150" y="93" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="null" mpsm="1">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <attachment type="int" label="Leave Days" attname="days" value=""/>
    <attachment type="text" label="Leave Reason" attname="reason" value=""/>
    <next targetID="A1878F04-2D3D-3D88-E3DA-59F5FBB94E2F" joints=""/>
  </node>
  <node id="A1878F04-2D3D-3D88-E3DA-59F5FBB94E2F" type="task" title="Please decide whether to approve leave or not" name="Leave waiting for your approval" x="110" y="226" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="null" mpsm="1">
    <taskto type="role" whom="Approver"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <attachment type="text" label="Your Comment" attname="approveComment" value=""/>
    <next option="1.Approve it." targetID="7CE979C9-5530-79C0-768F-59F637566ECF" joints=""/>
    <next option="2.Reject it." targetID="348CAF86-53E0-A373-6F51-59F657CCCF0E" joints=""/>
  </node>
  <node id="7CE979C9-5530-79C0-768F-59F637566ECF" type="task" title="Congratulation, your leave application has been approved." name="Your Leave was approved." x="461" y="231" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="null" mpsm="1">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next targetID="022434F3-87E5-21E2-4105-59F4A2A9FD68" joints=""/>
  </node>
  <node id="348CAF86-53E0-A373-6F51-59F657CCCF0E" type="task" title="Your leave has been rejected.&#xD;[p]Do you want to apply again?[/p]" name="Leave was rejected" x="486" y="90" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="null" mpsm="1">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next option="2.Give up" targetID="022434F3-87E5-21E2-4105-59F4A2A9FD68" joints=""/>
    <next option="1.Re-apply" targetID="F3518383-8E11-E6D2-A536-59F4CA5D114B" joints="362:54"/>
  </node>
</cf:workflow>

=== cnshsliu/cflow/data/istwft/tester1/0fbb0e9fba3b46f9863ab917dc0dd961.xml
<?xml version="1.0" encoding="UTF-8"?><cf:workflow xsi:schemaLocation="http://lkh.com/cflow ../schemas/wft.xsd" name="tobedelete" owner="LKH" acl="private" lastModified="2011-03-19T04:18:58" created="2011-03-19T04:18:58" xmlns:cf="http://lkh.com/cflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><node id="id_start" type="start" title="Start" name="Start" x="27" y="213">
 <next targetID="id_1"/><next targetID="id_2"/><next targetID="id_3"/></node><node id="id_end" type="end" title="End" name="End" x="738" y="213">
 <next targetID="id_end"/></node><node id="id_1" type="task" title="ID_1" name="ID_1"  acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="" mpsm="1">
 <taskto type="role" whom="starter"/>
 <mpcdc/>
 <oec/>
 <next targetID="id_AND"/></node><node id="id_2" type="task" title="ID_2" name="ID_2"  acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="" mpsm="1">
 <taskto type="role" whom="starter"/>
 <mpcdc/>
 <oec/>
 <next targetID="id_AND"/></node><node id="id_3" type="task" title="ID_3" name="ID_3"  acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="" mpsm="1">
 <taskto type="role" whom="starter"/>
 <mpcdc/>
 <oec/>
 <next targetID="id_AND"/></node><node id='id_AND' type='and'><next targetID='id_NULL'/></node><node id="id_NULL" type="task" title="ID_NULL" name="ID_NULL"  acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="" mpsm="1">
 <taskto type="role" whom="starter"/>
 <mpcdc/>
 <oec/>
 <next targetID="id_end"/></node></cf:workflow>

=== cnshsliu/cflow/data/vault/aliyun/cffde5ef7ef94be7a910316240426437.xml
<?xml version="1.0" encoding="UTF-8"?><cf:workflow xsi:schemaLocation="http://lkh.com/cflow ../schemas/wft.xsd" name="aaaa" owner="aliyun" acl="private" lastModified="2012-12-06T02:22:32" created="2012-12-06T02:22:32" xmlns:cf="http://lkh.com/cflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <node id="9BAF753D-9875-F593-1264-6C29F1B573AB" type="start" title="Start" name="Start" x="28" y="238">
    <next targetID="47FF4CE7-8924-E6E7-348C-6C2A10A6BF99" joints=""/>
  </node>
  <node id="6B8224B6-AC60-B2C2-C506-6C29F1BA50E5" type="end" title="End" name="End" x="708" y="238">
    <next targetID="6B8224B6-AC60-B2C2-C506-6C29F1BA50E5"/>
  </node>
  <node id="47FF4CE7-8924-E6E7-348C-6C2A10A6BF99" type="task" title="Task" name="Task" x="308" y="150" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="" mpsm="1">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next targetID="6B8224B6-AC60-B2C2-C506-6C29F1BA50E5" joints=""/>
    <next targetID="22CE3B1D-5930-E80F-3EC7-6C4502C578AB" joints="380:70"/>
  </node>
  <node id="22CE3B1D-5930-E80F-3EC7-6C4502C578AB" type="task" title="Task" name="Task" x="493" y="108" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="" mpsm="1">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next targetID="6B8224B6-AC60-B2C2-C506-6C29F1BA50E5" joints=""/>
  </node>
</cf:workflow>
