=== cnshsliu/cflow/schemas/wft.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) by Altova 
	(XMLSpy) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:cf="http://lkh.com/cflow" targetNamespace="http://lkh.com/cflow">
	<xs:simpleType name="aclType">
		<xs:restriction base="xs:string">
			<xs:pattern value="private|group|public" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="actorType">
		<xs:restriction base="xs:string">
			<xs:pattern value="role|person|group|RefertoNode" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="message">
		<xs:simpleContent>
			<xs:extension base="xs:string" />
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="attachmentType">
		<xs:restriction base="xs:string">
			<xs:pattern value="text|url|int|float|netext" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="mailto">
		<xs:attribute name="type" type="cf:actorType" use="required" />
		<xs:attribute name="whom" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="smsto">
		<xs:attribute name="type" type="cf:actorType" use="required" />
		<xs:attribute name="whom" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="taskto">
		<xs:sequence>
			<xs:element name="exceptme" type="cf:exceptme"
				maxOccurs="unbounded" minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="cf:actorType" use="required">
			<xs:annotation>
				<xs:documentation>
					role or person are two possilbe tyes for workflow
					template. For a process, type must be "person"
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="whom" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Role name or user id depends on the type of taskto
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="status" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					在进程中记录该用户的工作完成情况。在模板中不起作用；
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>

	</xs:complexType>
	<xs:complexType name="attachment">
		<xs:attribute name="type" type="cf:attachmentType"
			use="required" />
		<xs:attribute name="label" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					The promot for input
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="optional"
			default="">
			<xs:annotation>
				<xs:documentation>
					For template, value is normally not specified. for
					process, value should be input by user.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="attname" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					name of the attribute, should be a valid
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="usrid" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="sendmail">
		<xs:sequence>
			<xs:element name="mailto" type="cf:mailto" />
			<xs:element name="message" type="cf:message" />
		</xs:sequence>
		<xs:attribute name="subject" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="sendsms">
		<xs:sequence>
			<xs:element name="smsto" type="cf:smsto" />
			<xs:element name="message" type="cf:message" />
		</xs:sequence>
		<xs:attribute name="subject" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="role">
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>the name of a role</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Normally, the participant of a role is specified
					while process run. Workflow designer could assign value to a
					particular role as well.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="robotActions">
		<xs:choice>
			<xs:element name="sendmail" type="cf:sendmail" />
			<xs:element name="sendsms" type="cf:sendsms" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="nextType">
		<xs:attribute name="option" type="xs:string" default="DEFAULT">
			<xs:annotation>
				<xs:documentation>If options present for more than one next element,
					user must choice among these options, the route will depend on
					user's choice.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="targetID" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>id of the next node pointed to.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="node">
		<xs:annotation>
			<xs:documentation>a node of workflow</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="taskto" type="cf:taskto" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="preactions" type="cf:robotActions"
				minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Actions to be taken automaticlaly before any
						other acitons could occurs.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="sendmail" type="cf:sendmail"
				minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Send out an email
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="sendsms" type="cf:sendsms"
				minOccurs="0">
				<xs:annotation>
					<xs:documentation>Send out an SMS</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="attachment" type="cf:attachment"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="script" minOccurs="0">
				<xs:complexType mixed="false">
					<xs:simpleContent>
						<xs:extension base="xs:string" />
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="next" type="cf:nextType"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Occurance of next is 0 means that the node's
						next node is "end".
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="postactions" type="cf:robotActions"
				minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Actions to be taken automatically before this
						task could complete.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="mpcdc" maxOccurs="1" minOccurs="0"
				type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Multiple Person Completion Decision Code
					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element name="oec" maxOccurs="1" minOccurs="0"
				type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Option Evaluation Code
					</xs:documentation>
				</xs:annotation>

			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="cf:nodeType" use="optional"
			default="task">
			<xs:annotation>
				<xs:documentation>
					Whether this node is an automatic node which will be
					executed automatically.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="id" type="xs:string" use="required" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="title" type="xs:string" />
		<xs:attribute name="customizer" type="xs:string"></xs:attribute>
		<xs:attribute name="x" type="xs:int" />
		<xs:attribute name="y" type="xs:int" />
		<xs:attribute name="subWftUID" type="xs:string" />
		<xs:attribute name="subWftWG" type="xs:string" />
		<xs:attribute name="yy" type="xs:integer" />
		<xs:attribute name="mm" type="xs:integer" />
		<xs:attribute name="dd" type="xs:integer" />
		<xs:attribute name="hh" type="xs:integer" />
		<xs:attribute name="mi" type="xs:integer" />
		<xs:attribute name="timeingType" type="xs:string" />
		<xs:attribute name="mpsm" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					Multiple Person Sync Mode
				</xs:documentation>
			</xs:annotation>

		</xs:attribute>
		<xs:attribute name="acquirable" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="acqThreshold" type="xs:int" default="1"></xs:attribute>
		<xs:attribute name="allowRoleChange" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="roleToChange" type="xs:string"
			default="all">
		</xs:attribute>
		<xs:attribute name="allowDelegate" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="allowAdhoc" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="allowBack" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="repeatthresholdtype" type="xs:string"></xs:attribute>
		<xs:attribute name="repeatthreshold" type="xs:string"></xs:attribute>
		<xs:attribute name="repeatcron" type="xs:string"></xs:attribute>
		<xs:attribute name="form" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:element name="workflow">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="role" type="cf:role" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="node" type="cf:node" minOccurs="0"
					maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="owner" type="xs:string" use="required" />
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="origin" type="xs:string"></xs:attribute>
			<xs:attribute name="memo" type="xs:string" use="optional" />
			<xs:attribute name="customizer" type="xs:string"></xs:attribute>
			<xs:attribute name="pbo" type="xs:string"></xs:attribute>
			<xs:attribute name="acl" type="cf:aclType" use="required" />
			<xs:attribute name="lastModified" type="xs:dateTime"
				use="required" />
			<xs:attribute name="created" type="xs:dateTime"
				use="required" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="processStatusType">
		<xs:restriction base="xs:string">
			<xs:pattern value="running|suspended|finished|canceled" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="nodeType">
		<xs:restriction base="xs:string">
			<xs:pattern value="task|notify|sub|timer|and|or|round|script|start|end|ground" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="workStatusType">
		<xs:restriction base="xs:string">
			<xs:pattern value="running|suspended|finished|ignored" />
		</xs:restriction>
	</xs:simpleType>
	<!--Process definition start here -->
	<xs:complexType name="work">
		<xs:sequence>
			<xs:element name="taskto" type="cf:taskto"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Person to whom this task will be delivered.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="attachment" type="cf:attachment"
				minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						An attachment is an information need to be input
						by "taskto"
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="options" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="option" type="xs:string"
							maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="isMultipleSelection"
						type="xs:boolean" default="false" />
				</xs:complexType>
			</xs:element>
			<xs:element name="mpcdc" maxOccurs="1" minOccurs="0"
				type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Multiple Person Completion Decision Code
					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element name="oec" maxOccurs="1" minOccurs="0"
				type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Option Evaluation Code
					</xs:documentation>
				</xs:annotation>

			</xs:element>
			<xs:element name="log" type="cf:log" maxOccurs="unbounded"
				minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="sessid" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					session id a UID string
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="roundid" type="xs:string"></xs:attribute>
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="title" type="xs:string" />
		<xs:attribute name="customizer" type="xs:string"></xs:attribute>
		<xs:attribute name="type" type="xs:string" />
		<xs:attribute name="nodeid" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					id of corresponding workflow node.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="createdAt" type="xs:dateTime">
			<xs:annotation>
				<xs:documentation>
					Time when this work was yarked
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="completedAt" type="xs:dateTime">
			<xs:annotation>
				<xs:documentation>
					Time when this work was completed
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="completedBy" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					Who commit this work
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="status" type="cf:workStatusType"
			default="running" />
		<xs:attribute name="decision" type="xs:string"
			default="DEFAULT">
			<xs:annotation>
				<xs:documentation>
					The option user selected
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="mpsm" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					Multiple Person Sync Mode
				</xs:documentation>
			</xs:annotation>

		</xs:attribute>
		<xs:attribute name="sysmsg" type="xs:string">
			<xs:annotation>
				<xs:documentation>System Message</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="acquirable" type="xs:boolean"
			default="false">
		</xs:attribute>
		<xs:attribute name="acqThreshold" type="xs:int" default="1"></xs:attribute>
		<xs:attribute name="allowDelegate" type="xs:boolean"
			default="true">
		</xs:attribute>
		<xs:attribute name="allowAdhoc" type="xs:boolean"
			default="true">
		</xs:attribute>
		<xs:attribute name="repeatthresholdtype" type="xs:string"></xs:attribute>
		<xs:attribute name="repeatthreshold" type="xs:string"></xs:attribute>
		<xs:attribute name="repeatcron" type="xs:string"></xs:attribute>
		<xs:attribute name="form" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ProcessT">
		<xs:annotation>
			<xs:documentation>用于记录</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="role" type="cf:role" minOccurs="0"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Role pair (name and value) for a template,
						normally the value does not present but workflow
						designer can set value for a role whenever
						needed. For a process, the value should present.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="work" type="cf:work"
				maxOccurs="unbounded" />
			<xs:element name="team" type="cf:teamType" maxOccurs="1"
				minOccurs="1">
			</xs:element>
			<xs:element name="attachment" type="cf:attachment"
				maxOccurs="unbounded" minOccurs="0">
				<xs:annotation>
					<xs:documentation>用于记录流程级参数</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string">
			<xs:annotation>
				<xs:documentation>id of the process</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="roundid" type="xs:string"></xs:attribute>
		<xs:attribute name="startby" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					userid who has started this process
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="startat" type="xs:dateTime">
			<xs:annotation>
				<xs:documentation>
					When this process was started
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="endat" type="xs:dateTime">
			<xs:annotation>
				<xs:documentation>
					When this process finished
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="status" type="cf:processStatusType">
			<xs:annotation>
				<xs:documentation>
					The status of the process
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="wftid" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					id of the corresponding workflow template
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="origin" type="xs:string"></xs:attribute>
		<xs:attribute name="wftname" type="xs:string" />
		<xs:attribute name="customizer" type="xs:string"></xs:attribute>
		<xs:attribute name="teamid" type="xs:string" />
		<xs:attribute name="pbo" type="xs:string"></xs:attribute>
		<xs:attribute name="lastError" type="xs:string"></xs:attribute>
		<xs:attribute name="parentProcessId" type="xs:string" />
		<xs:attribute name="parentProcessNodeId" type="xs:string" />
		<xs:attribute name="parentProcessSessId" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:element name="process" type="cf:ProcessT">
		<xs:annotation>
			<xs:documentation>Process is instantiated from a workflow template
			</xs:documentation>
		</xs:annotation>
	</xs:element>
	<!--Process definition end here -->

	<xs:complexType name="log">
		<xs:sequence>
			<xs:element name="attachment" type="cf:attachment" maxOccurs="unbounded" minOccurs="0"></xs:element>
		</xs:sequence>
		<xs:attribute name="usrid" type="xs:string"></xs:attribute>
		<xs:attribute name="timestamp" type="xs:dateTime"></xs:attribute>
		<xs:attribute name="option" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:simpleType name="mpsmType">
		<xs:restriction base="xs:string"></xs:restriction>
	</xs:simpleType>


	<xs:complexType name="exceptme">
		<xs:attribute name="nodeid" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="delegate">
		<xs:attribute name="fromuid" type="xs:string"></xs:attribute>
		<xs:attribute name="touid" type="xs:string"></xs:attribute>
		<xs:attribute name="delegateat" type="xs:dateTime"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="teamType">
		<xs:sequence>
			<xs:element name="role" type="cf:role" maxOccurs="unbounded" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== cnshsliu/cflow/data/vault/luke-EC7AB30A-E079-745E-D8F7-FE3D02983198.xml
<?xml version="1.0" encoding="UTF-8"?>
<cf:workflow xsi:schemaLocation="http://lkh.com/cflow ../schemas/wft.xsd" name="aaa" owner="luke" acl="private" lastModified="2009-06-20T23:25:48" created="2009-06-20T23:25:48" xmlns:cf="http://lkh.com/cflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <node id="7F15A019-160B-1F31-B6F2-FE3D027AD1E1" type="start" title="Start" name="Start" x="27" y="204">
    <next targetID="3CC317EA-F88C-30D7-11DD-FE3D2248E794"/>
  </node>
  <node id="F153CE65-0EB7-A56C-B59E-FE3D0284C604" type="end" title="End" name="End" x="748" y="204">
    <next targetID="F153CE65-0EB7-A56C-B59E-FE3D0284C604"/>
  </node>
  <node id="3CC317EA-F88C-30D7-11DD-FE3D2248E794" type="task" title="Task" name="Task" x="321" y="167">
    <taskto type="person" whom="luke"/>
    <next targetID="F153CE65-0EB7-A56C-B59E-FE3D0284C604"/>
  </node>
</cf:workflow>

=== cnshsliu/cflow/data/istwft/aliyun/3969ecabf42046f2a295017fe0b4024c.xml
<?xml version="1.0" encoding="UTF-8"?><cf:workflow xsi:schemaLocation="http://lkh.com/cflow ../schemas/wft.xsd" name="Demo_JAVASCRIPT" owner="aliyun" acl="private" lastModified="2012-11-27T11:09:44" created="2012-11-27T11:09:44" xmlns:cf="http://lkh.com/cflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <node id="7EBD6CB5-42D0-C653-4DE6-EAF5D9D869D1" type="start" title="Start" name="Start" x="28" y="228">
    <next targetID="12EDDD5E-4646-3A8A-7DC9-EAF60250705D"/>
  </node>
  <node id="0108D032-64BC-52C4-EB08-EAF5D9DC36B9" type="end" title="End" name="End" x="455" y="220">
    <next targetID="0108D032-64BC-52C4-EB08-EAF5D9DC36B9"/>
  </node>
  <node id="12EDDD5E-4646-3A8A-7DC9-EAF60250705D" type="task" title="This demo shows how to [u]integrate with a JAVA program[/u], the JAVA class this workflow invoke must resides in MWF server's classpath. &#xD;The Java in this demo will route the process by leave days, go to [color=red] LONG [/color] if days are more than 10.  or elase go to [color=red]SHORT[/color]. (See variable definition in Attachments tab)" name="Leaving Application" x="84" y="227" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="" mpsm="1">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <attachment type="int" label="Leave Days" attname="days" value=""/>
    <attachment type="text" label="Leave Reason" attname="reason" value=""/>
    <next targetID="14D169BC-F935-982E-AD17-EAF96CB21650"/>
  </node>
  <node id="14D169BC-F935-982E-AD17-EAF96CB21650" type="script" title="Script" name="Script" x="247" y="220">
    <script>if(days&gt;10)     data.RETURN="long"; else    data.RETURN="short";data.myContextValue="myvalue";</script>
    <next option="long" targetID="A2D19FEC-953A-BAE7-A270-EAF99089E7D8"/>
    <next option="short" targetID="86D55C63-56EE-B2D0-988D-EAF9E950825F"/>
    <next option="onerror" targetID="FC90ACF3-09DC-61BC-FE63-EB0E85DF0F37"/>
  </node>
  <node id="A2D19FEC-953A-BAE7-A270-EAF99089E7D8" type="task" title="Your leaving is long" name="Long Leave" x="314" y="149" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="" mpsm="1">
    <taskto type="role" whom="starter">
      <exceptme nodeid="12EDDD5E-4646-3A8A-7DC9-EAF60250705D"/>
    </taskto>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next targetID="0108D032-64BC-52C4-EB08-EAF5D9DC36B9"/>
  </node>
  <node id="86D55C63-56EE-B2D0-988D-EAF9E950825F" type="task" title="Your Leaving is short" name="Short Leave" x="316" y="271" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="" mpsm="1">
    <taskto type="role" whom="starter">
      <exceptme nodeid="12EDDD5E-4646-3A8A-7DC9-EAF60250705D"/>
    </taskto>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next targetID="0108D032-64BC-52C4-EB08-EAF5D9DC36B9"/>
  </node>
  <node id="FC90ACF3-09DC-61BC-FE63-EB0E85DF0F37" type="task" title="Error occured" name="Error occured" x="317" y="368" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" form="ERROR" mpsm="1">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next targetID="0108D032-64BC-52C4-EB08-EAF5D9DC36B9"/>
  </node>
</cf:workflow>

=== cnshsliu/cflow/data/vault/luke.yuz.tsai-84159D92-6EC1-33A8-2DED-034473FF371C.xml
<?xml version="1.0" encoding="UTF-8"?>
<cf:workflow xsi:schemaLocation="http://lkh.com/cflow ../schemas/wft.xsd" name="testBBCode" owner="luke.yuz.tsai" acl="private" lastModified="2010-11-01T15:06:17" created="2010-11-01T15:06:17" xmlns:cf="http://lkh.com/cflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <node id="D7863580-78C6-8FA3-A123-034473F77AAB" type="start" title="Start" name="Start" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="true" allowAdhoc="true" roleToChange="all" x="27" y="204" mpsm="">
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next targetID="AAD82FF9-76A9-2C57-0BD6-034499D3DB59"/>
  </node>
  <node id="274553C7-4842-72A1-FEF5-034473FCF42B" type="end" title="End" name="End" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="true" allowAdhoc="true" roleToChange="all" x="748" y="204" mpsm="">
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next targetID="274553C7-4842-72A1-FEF5-034473FCF42B"/>
  </node>
  <node id="AAD82FF9-76A9-2C57-0BD6-034499D3DB59" type="task" title="[h3]Hello, this is my test[/h3]&#xD;[img]http://www.lokoho.com/cflow/images/logo.png[/img]" name="bbCode测试节点" acquirable="false" acqThreshold="1" allowRoleChange="false" allowDelegate="false" allowAdhoc="false" roleToChange="all" x="184" y="138" mpsm="">
    <taskto type="role" whom="starter"/>
    <mpcdc>null</mpcdc>
    <oec>null</oec>
    <next targetID="274553C7-4842-72A1-FEF5-034473FCF42B"/>
  </node>
</cf:workflow>
